import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
// import Navbar from '../components/Navbar'
export async function getServerSideProps(context) {
 
  const response = await fetch('http://localhost:3000/api/blogs')
  let data = await response.json()
  // console.log(data)
  // getBlogs(data)
  data = data.slice(0,3)

return { props: { data } };
};

export default function Home(props) {
  const [blogs, getBlogs] = useState(props.data)
  // const fetchBlogs = async () => {
  //   const response = await fetch('http://localhost:3000/api/blogs')
  //   const data = await response.json()
  //   // console.log(data)
  //   getBlogs(data)
  // }
  // useEffect(() => {
  //   fetchBlogs()
  // }, [])
  return (
    <>
      <style jsx>
        {`
    syntax of writing internal css
    #myPara {
      color : red;
    }
    
    `}
      </style>
      <div className={styles.container}>
        <Head>
          <title>De-Coders</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="keywords" content="De-Code , De-Coders, blog, blogpost" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* importing navbar only in Home page
     <Navbar/> 
     but we have already imported it in _app so no need*/}
        <main className={styles.main}>
          <h1 className={styles.title}>
            &lt;De-Coders/&gt;
          </h1>

          <p className={styles.description} id='myPara'>
            Lets De-Code together

          </p>
          <Image src={'/homeImg.jpg'} width={300} height={200} id={styles.myImg} />
          <div className={styles.blogs}>
            {
              blogs ? blogs.map((el, index) => {
                return <Link href={`/blogpost/${el.slug}`} className={styles.blog}>
                  <h3 className="blogTitle">
                    {el.title}
                  </h3>
                  <p className="blogItem">
                    {el.content.slice(0,100)}...
                  </p>

                </Link>
              }) : ""
            }

          </div>

        </main>


      </div>
    </>
  )
}
